name = "landing"
title = "MongoDB Documentation"
default_domain = "landing"

[constants]
version = 4.0
package-name-org = "docs-landing"
pgp-version = "{+version+}"

[deprecated_versions]
bi-connector = ["v2.9", "v2.8", "v2.7", "v2.6", "v2.5", "v2.4", "v2.3", "v2.2", "v2.1", "v2.0", "v1.1"]
kubernetes-operator = ["v0.12", "v0.11", "v0.10", "v0.9", "v0.8"]
manual = ["v3.4", "v3.2", "v3.0", "v2.6", "v2.4", "v2.2"]
mms = ["v3.6", "v3.4", "v2.0", "v1.8", "v1.6", "v1.5", "v1.4", "v1.3", "v1.2", "v1.1"]
mongocli = ["v0.5.0", "v0.2.0", "v0.1.0", "v0.0.4", "v0.0.3"]
ruby-driver = ["v2.3", "v2.2", "v2.0", "v1.x"]
spark-connector = ["v2.0", "v1.1"]
